; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:megaatmega1280]
platform = atmelavr
board = megaatmega1280
framework = arduino


; 💡 여기서 빌드하고 싶은 강좌 파일의 경로만 지정합니다.
; 예: 1강을 테스트하고 싶을 때
src_filter = +<main.cpp>
; src_filter = +<01_switch_lamp.cpp> 

; 예: 나중에 4강을 테스트하고 싶다면 아래처럼 변경하시면 됩니다.
; src_filter = +<04_sensor_cyl.cpp>
